// Who made this access point, from the IEEE Registration Authority's OUI registries.
//
// resources/oui.json is generated by scripts/fetch-oui.mjs and bundled at build time, exactly as
// resources/chipsets.json is. Lookup is longest-prefix: IEEE assigns /24 (MA-L), /28 (MA-M) and
// /36 (MA-S) blocks, and a /36 address matched only against /24 resolves to "IEEE Registration
// Authority", which is true and useless.

import ouiRaw from '../../../resources/oui.json'

const db = ouiRaw as unknown as Record<string, string>

/** Strip separators and case, so `84:78:48:…`, `84-78-48-…` and `847848…` all look the same. */
export function normalizeMac(mac: string): string {
  return mac.replace(/[^0-9a-fA-F]/g, '').toLowerCase()
}

/** The registered organisation for an address, trying the finest registry first. */
export function lookupOui(mac: string): string | undefined {
  const hex = normalizeMac(mac)
  if (hex.length < 6) return undefined
  return db[hex.slice(0, 9)] ?? db[hex.slice(0, 7)] ?? db[hex.slice(0, 6)]
}

/**
 * Vendor elements that say nothing about who built the access point, and would actively mislead.
 *
 * The first three are protocol markers riding in almost every beacon — reading them as the maker
 * would report most of the world's Wi-Fi as Microsoft. The rest are silicon vendors whose elements
 * appear in beacons from everyone else's products, so they answer "whose chipset" rather than
 * "whose product", which is not the question the vendor column asks.
 */
export const UNINFORMATIVE_OUIS = new Set([
  '0050f2', // Microsoft — WPA, WMM and WPS elements
  '000fac', // IEEE 802.11 — RSN
  '506f9a', // Wi-Fi Alliance — P2P, Hotspot 2.0
  '8cfdf0', // Qualcomm
  '001018', // Broadcom
  '00904c', // Broadcom / Epigram
  '000c43' // MediaTek / Ralink
])

/**
 * Name the maker of an access point.
 *
 * A globally administered BSSID carries its manufacturer in the first three octets, and that is
 * the reliable answer. A locally administered one does not — modern access points invent a BSSID
 * per SSID — so there the beacon's own vendor elements are the only remaining signal. That is a
 * weaker inference, which is why the uninformative ones are filtered out rather than guessed at,
 * and why `locallyAdministered` stays on the record for the UI to show alongside.
 */
export function resolveVendor(
  bssid: string,
  locallyAdministered: boolean,
  vendorOuis: string[] = []
): string | undefined {
  if (!locallyAdministered) return lookupOui(bssid)
  for (const oui of vendorOuis) {
    const hex = normalizeMac(oui)
    if (UNINFORMATIVE_OUIS.has(hex)) continue
    const name = lookupOui(hex)
    if (name) return name
  }
  return undefined
}
